routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/', 'HomeController@index')->name('home');

Route::post('user/reset/password', 'Auth\ResetPasswordController@reset')->name('auth.reset')->middleware('auth');

Route::middleware(['auth', 'role:manage_users'])->namespace('Auth')->prefix('user')->name('auth.')->group(function () {
    Route::get('show', 'ShowController')->name('show');

    Route::get('edit/{id}', 'EditController@edit')->name('edit');

    Route::post('update', 'EditController@update')->name('update');

    Route::get('create', 'CreateController@create')->name('create');

    Route::post('insert', 'CreateController@insert')->name('insert');
});


Route::middleware('auth')->namespace('Ticket')->name('ticket.')->prefix('tickets')->group(function () {

    Route::middleware('role:create_ticket')->group(function () {
        Route::get('create', 'CreateController@create')->name('create');

        Route::post('insert', 'CreateController@insert')->name('insert');

        Route::get('edit/{id}', 'EditController@edit')->name('edit');

        Route::post('update', 'EditController@update')->name('update');
    });

    Route::middleware('role:response_ticket')->group(function () {
        Route::post('response', 'ResponseController@response')->name('response');
    });

    Route::get('view/{id}', 'ResponseController@view')->name('view');

    Route::post('assign', 'AssignController')->name('assign')->middleware('role:assign_ticket');

    Route::get('show', 'ShowController')->name('show');
});

app/Http/Controllers/Ticket/AssignController.php
<?php

namespace App\Http\Controllers\Ticket;

use App\Services\TicketService;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AssignController extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Services\TicketService $ticketService
     * @return \Illuminate\Http\Response
     */
    public function __invoke(Request $request, TicketService $ticketService)
    {
        $validation = $request->validate([
            'id_solicitud' => 'required|exists:solicitud,id_solicitud',
            'user_respuesta_id' => 'required|exists:users,id_user'
        ]);

        $ticketService->update($request->all());

        return redirect(route('ticket.show'));
    }
}

app/Http/Controllers/Ticket/CreateController.php
<?php

namespace App\Http\Controllers\Ticket;

use App\Http\Controllers\Controller;
use App\Models\CatSistema;
use App\Services\TicketService;
use Illuminate\Http\Request;

class CreateController extends Controller
{
    public function create()
    {
        return view('tickets.create')
            ->with('systems', CatSistema::all());
    }

    public function insert(Request $request, TicketService $ticketService)
    {
        $validation = $request->validate([
            'incidencia' => 'required|string',
            'sistema_id' => 'required|integer',
            'imagenes.*' => 'required|image|mimes:jpg,jpeg,png|max:1000'
        ]);

        $ticketService->insert($request->all());

        return redirect(route('ticket.show'));
    }
}

app/Http/Controllers/Ticket/EditController.php
<?php

namespace App\Http\Controllers\Ticket;

use App\Http\Controllers\Controller;
use App\Models\CatSistema;
use App\Models\Solicitud;
use App\Services\TicketService;
use App\Services\VerifyService;
use Illuminate\Http\Request;

class EditController extends Controller
{
    public function edit($id)
    {
        return view('tickets.edit')->with([
            'ticket' => Solicitud::findOrFail(decrypt($id)),
            'systems' => CatSistema::all()
        ]);
    }

    public function update(Request $request, TicketService $ticketService, VerifyService $verify)
    {
        if ($verify->verifyEmpty($request->all())) {
            return back();
        }

        $validation = $request->validate([
            'id_ticket' => 'required',
            'incidencia' => 'nullable|string',
            'imagenes.*' => 'nullable|image|max:1000',
            'sistema_id' => 'nullable|alpha'
        ]);

        $ticketService->update($request->all());
    }
}

app/Http/Controllers/Ticket/ResponseController.php
<?php

namespace App\Http\Controllers\Ticket;

use App\Http\Controllers\Controller;
use App\Models\Solicitud;
use App\Services\TicketService;
use Illuminate\Http\Request;

class ResponseController extends Controller
{
    public function view($id)
    {
        return view('tickets.response')
            ->with('ticket', Solicitud::findOrFail(decrypt($id)));
    }

    public function response(Request $request, TicketService $ticketService)
    {
        $validation = $request->validate([
            'id_solicitud' => 'required|exists:solicitud,id_solicitud',
            'respuesta' => 'required|string',
            'estatus' => [
                'required',
                'regex:/RESUELTO/'
            ]
        ]);

        $ticketService->update($request->all());

        return redirect(route('ticket.show'));
    }
}

app/Http/Controllers/Ticket/ShowController.php
<?php

namespace App\Http\Controllers\Ticket;

use App\Http\Controllers\Controller;
use App\Models\Role;
use App\Models\Solicitud;
use Illuminate\Support\Facades\Auth;

class ShowController extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @return \Illuminate\Http\Response
     */
    public function __invoke()
    {
        if (Auth::user()->hasRole('assign_ticket')) {
            $tickets = Solicitud::with('system', 'userCreate', 'userResponse')
                ->get();
        } elseif (Auth::user()->hasRole('response_ticket')) {
            $tickets = Solicitud::with('system', 'userCreate', 'userResponse')
                ->where([
                    ['user_creacion_id', '=', Auth::id()],
                    ['estatus', '=', 'PENDIENTE']
                ])
                ->orWhere('user_respuesta_id', Auth::id())
                ->get();
        } else {
            $tickets = Solicitud::with('system', 'userCreate', 'userResponse')
                ->where('user_creacion_id', Auth::id())
                ->orWhere('user_respuesta_id', Auth::id())
                ->get();
        }

        foreach ($tickets as $ticket) {
            $ticket->id_encrypt = encrypt($ticket->id_solicitud);
        }

        return view('tickets.show')->with([
            'tickets' => $tickets,
            'users' => Role::find('2')->users()->get()
        ]);
    }
}

resources/views/tickets/assign.blade.php
<div id="modal_assign" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content text-center">
            <div class="modal-header">
                <h5 class="modal-title">Asignar Usuario</h5>
            </div>

            <form method="post" action="{{ route('ticket.assign') }}">
                @csrf()
                <div class="modal-body">
                    <div class="form-group has-feedback">
                        <input name="id_solicitud" value="{{ $ticket->id_solicitud }}" hidden="hidden">

                        <select name="user_respuesta_id" class="select" data-placeholder="Selecciona a un usuario" required="required">
                            <option></option>
                            @foreach($users as $user)
                                <option value="{{ $user->id_user }}">{{ $user->nombre . ' ' . $user->primer_apellido . ' ' . $user->segundo_apellido }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>

                <div class="modal-footer text-center">
                    <button type="submit" class="btn btn-primary">Asignar!</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/tickets/create.blade.php
@extends('layouts.app')

@section('title','Crear Ticket')

@push('assets')
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/selects/select2.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/uploaders/fileinput.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/styling/uniform.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/custom/editar_ticket.js') }}"></script>
@endpush

@section('content')
    <div class="panel panel-flat">
        <div class="panel-heading">
            <h5 class="panel-title">Nuevo Ticket</h5>
        </div>
        <div class="panel-body">
            <form method="post" action="{{ route('ticket.insert') }}" enctype="multipart/form-data">
                @csrf
                <div class="form-group">
                    <label for="incidencia">Incidencia</label>
                    <textarea class="form-control" name="incidencia" id="incidencia" rows="5" cols="5"
                              onkeyup="toUpperCase(this)" required="required"></textarea>

                    @if ($errors->has('incidencia'))
                        <span class="help-block text-danger">
                                <i class="icon-cancel-circle2 position-left"></i>
                                {{ $errors->first('incidencia') }}
                        </span>
                    @endif
                </div>

                <div class="form-group">
                    <label for="id_sistema">Sistema</label>
                    <select data-placeholder="Selecciona un sistema" name="sistema_id" id="id_sistema" class="select"
                            required="required">
                        <option></option>
                        @foreach($systems as $system)
                            <option value="{{ $system->id_sistema }}">{{ $system->sistema }}</option>
                        @endforeach
                    </select>

                    @if ($errors->has('sistema_id'))
                        <span class="help-block text-danger">
                                <i class="icon-cancel-circle2 position-left"></i>
                                Verifica que ingreses bien tu información
                        </span>
                    @endif
                </div>

                <div class="form-group">
                    <label class="display-block">Agrega más imagenes:</label>
                    <input type="file" name="imagenes[]" class="file-input" multiple="multiple"
                           data-show-upload="false">

                    @if ($errors->has('imagenes'))
                        <span class="help-block text-danger">
                                <i class="icon-cancel-circle2 position-left"></i>
                                Verifica que ingreses bien tu información
                        </span>
                    @endif
                </div>

                <div class="form-group text-right">
                    <a href="{{ route('home') }}">
                        <button type="button" class="btn btn-danger">Cancelar<i
                                class="icon-arrow-left13 position-right"></i></button>
                    </a>
                    <button type="submit" class="btn btn-primary">Guardar datos<i
                            class="icon-arrow-right14 position-right"></i></button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/tickets/edit.blade.php
@extends('layouts.app')

@push('assets')
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/selects/select2.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/uploaders/fileinput.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/styling/uniform.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/custom/editar_ticket.js') }}"></script>
@endpush

@section('title', 'Editar Ticket')

@section('content')
    <div class="panel panel-flat">
        <div class="panel-heading">
            <h6 class="panel-title">Editar Ticket</h6>
        </div>

        <div class="panel-body">
            <form method="post" action="{{ route('ticket.update') }}" enctype="multipart/form-data">
                @csrf
                <div class="form-group">
                    <label>Descripción de la Incidencia:</label>
                    <textarea rows="5" cols="5" class="form-control" placeholder="{{ $ticket->incidencia }}"
                              readonly="readonly"></textarea>
                </div>

                <div class="form-group">
                    <label>Información adicional:</label>
                    <span class="help-block">Esta información se agregara a la descripción de la incidencia</span>
                    <textarea rows="5" cols="5" class="form-control" name="incidencia" placeholder="Opcional" onkeyup="toUpperCase(this)"></textarea>

                    @if ($errors->has('incidencia'))
                        <span class="help-block text-danger">
                                <i class="icon-cancel-circle2 position-left"></i>
                                Verifica tu información
                        </span>
                    @endif
                </div>

                <div class="form-group">
                    <label class="display-block">Agrega más imagenes:</label>
                    <input type="file" name="imagenes[]" class="file-input" multiple="multiple" data-show-upload="false">

                    @if ($errors->has('imagenes'))
                        <span class="help-block text-danger">
                                <i class="icon-cancel-circle2 position-left"></i>
                                {{ $errors->first('imagenes') }}
                            </span>
                    @endif
                </div>

                <div class="form-group">
                    <label for="id_sistema">Sistema Asociado</label>
                    <select data-placeholder="{{ $ticket->system->sistema }}" class="select" name="id_sistema" id="id_sistema">
                        <option></option>
                        @foreach($systems as $system)
                            <option value="{{ $system->id_sistema }}">{{ $system->sistema }}</option>
                        @endforeach
                    </select>

                    @if ($errors->has('id_sistema'))
                        <span class="help-block text-danger">
                                <i class="icon-cancel-circle2 position-left"></i>
                                Verifica tu información
                            </span>
                    @endif
                </div>

                <div class="form-group text-right">
                    <a href="{{ route('home') }}">
                        <button type="button" class="btn btn-danger">Cancelar<i
                                class="icon-arrow-left13 position-right"></i></button>
                    </a>
                    <button type="submit" class="btn btn-primary">Guardar datos<i
                            class="icon-arrow-right14 position-right"></i></button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/tickets/response.blade.php
@extends('layouts.app')
@push('assets')
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/selects/select2.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/styling/uniform.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/media/fancybox.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/form_layouts.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/components_thumbnails.js') }}"></script>
@endpush
@section('title', 'Responder Ticket')
@section('content')
    <div class="panel panel-flat">
        <div class="panel-heading">
            <h5 class="panel-title">Responder Ticket</h5>
        </div>

        <div class="panel-body">
            <div class="form-group">
                <label for="system">Sistema:</label>
                <input id="system" value="{{ $ticket->system->sistema }}" class="form-control" readonly="readonly">
            </div>

            <div class="form-group">
                <label for="date">Fecha de solicitud:</label>
                <input id="date" value="{{ $ticket->created_at }}" class="form-control" readonly="readonly">
            </div>

            <div class="form-group">
                <label for="incidence">Incidencia:</label>
                <textarea id="incidence" class="form-control" placeholder="{{ $ticket->incidencia }}" readonly="readonly" rows="4"></textarea>
            </div>

            <div class="row">
                @foreach($ticket->images as $image)
                    <div class="col-xs-6 col-sm-3">
                        <div class="thumbnail">
                            <a href="data:image/png;base64,{{ $image->imagen }}" data-popup="lightbox">
                                <img src="data:image/png;base64,{{ $image->imagen }}" alt="">
                            </a>
                        </div>
                    </div>
                @endforeach
            </div>

            <form method="post" action="{{ route('ticket.response') }}">
                @csrf()
                <input name="id_solicitud" value="{{ $ticket->id_solicitud }}" hidden="hidden">
                <input name="estatus" value="RESUELTO" hidden="hidden">

                <div class="form-group">
                    <label>Respuesta:</label>
                    <textarea class="form-control" name="respuesta" placeholder="Respuesta de la solicitud" rows="4" onkeyup="toUpperCase(this)"></textarea>
                </div>

                <div class="form-group" align="right">
                    <button type="submit" class="btn btn-primary">Enviar respuesta</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/tickets/show.blade.php
@extends('layouts.app')

@section('title','Tickets')

@push('assets')
    <script type="text/javascript" src="{{ asset('assets/js/plugins/tables/datatables/datatables.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/selects/select2.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/custom/datatable_tickets.js') }}"></script>
@endpush

@section('content')
    <div class="panel panel-flat">
        <div class="panel-heading">
            <h5 class="panel-title">Tickets</h5>
        </div>
        <div class="panel-body">
            <div class="form-group">
                Listado de todos los tickets que se tienen asociados.
            </div>
            <div class="form-group">
                <table class="table datatable-basic dataTable table-hover">
                    <thead>
                    <tr>
                        <th>Folio Ticket</th>
                        <th>Incidencia</th>
                        <th>Fecha de Registro</th>
                        <th>Sistema</th>
                        <th>Estado</th>
                        @role('assign_ticket')
                        <th>Asignado a:</th>
                        @endrole
                        <th>Acciones</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($tickets as $ticket)
                        <tr>
                            <td>{{ $ticket->id_solicitud }}</td>
                            <td>{{ substr($ticket->incidencia, 0, 70) . '...' }}</td>
                            <td>{{ $ticket->created_at }}</td>
                            <td>{{ $ticket->system->sistema }}</td>
                            <td><span class="label label-{{ $ticket->estatus == 'PENDIENTE' ? "info":"success" }}">
                                    {{ $ticket->estatus }}
                                </span></td>
                            @role('assign_ticket')
                            <td>{{ $ticket->userResponse ? $ticket->userResponse->nombre : 'SIN ASIGNAR' }}</td>
                            @endrole
                            <td class="text-center">
                                <ul class="icons-list">
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                            <i class="icon-menu9"></i>
                                        </a>
                                        <ul class="dropdown-menu dropdown-menu-right">
                                            @role('assign_ticket')
                                            @if($ticket->estatus == 'PENDIENTE')
                                                <li>
                                                    <a href="" data-toggle="modal" data-target="#modal_assign">
                                                        <i class="glyphicon glyphicon-pushpin position-left"></i>
                                                        Asignar
                                                    </a>
                                                </li>
                                            @endif
                                            @endrole

                                            @role('create_ticket')
                                            @if($ticket->estatus == 'PENDIENTE' && !($ticket->userResponse))
                                                <li>
                                                    <a href="{{ route('ticket.edit', ['id' => $ticket->id_encrypt]) }}">
                                                        <i class="icon-pencil4 position-left"></i> Editar
                                                    </a>
                                                </li>
                                            @endif
                                            @endrole

                                            @role('response_ticket')
                                            @if($ticket->estatus == 'PENDIENTE')
                                                <li>
                                                    <a href="{{ route('ticket.view', ['id' => $ticket->id_encrypt]) }}">
                                                        <i class="icon-reply position-left"></i> Responder
                                                    </a>
                                                </li>
                                            @endif
                                            @endrole

                                            @if($ticket->estatus == 'RESUELTO' || Auth::user()->hasRole('assign_ticket'))
                                                <li>
                                                    <a href="{{ route('ticket.view', ['id' => $ticket->id_encrypt]) }}">
                                                        <i class="icon-reply position-left"></i> Ver
                                                    </a>
                                                </li>
                                            @endif
                                        </ul>
                                    </li>
                                </ul>
                            </td>
                        </tr>

                        @role('assign_ticket')
                        @if($ticket->estatus == 'PENDIENTE')
                            @include('tickets.assign')
                        @endif
                        @endrole
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection